---
title: "Project Overview"
editor: visual
---

## Project Overview

This project is intended to evaluate various metrics of the Baltimore Orioles baseball team when they play games within the breeding grounds and during the breeding season of the Baltimore oriole bird relative to when they play teams outside of the bird's breeding grounds and breeding season. Using eBird data from [The Cornell Lab of Ornithology](https://ebird.org/home) I divided the baseball season into four bird breeding seasons: Pre-breeding Migratory, Breeding, Post-breeding Migratory, and Non-breeding/Wintering. I then defined geographic breeding season "ranges" across the United States and Canada based on where the oriole had been observed during each of the four breeding seasons. Next, I used game-level data from the baseball statistics website [Retrosheet](https://www.retrosheet.org/) to find dates and locations for Orioles games each year from 2012 to 2021 to find when the Orioles played (a) *during* each of the bird's breeding seasons and (b) *within* each of the bird's geographic breeding season ranges. Tables were then made using the same Retrosheet data to make intra- and inter-breeding season comparisons of various aggregate hitting, pitching, and fielding statistics.

This project's primary goal is to serve as a practical exercise wherein I apply skills learned this semester for exploring, manipulating, and visualizing spatial data. I also combine two allegedly unrelated data sources, one spatial (bird sightings) and one not spatial (baseball game statistics), to create at least one new and novel data set to help humankind finally begin elucidating the mysterious relationship between sports teams and the animals upon which they and their legions of fans build their identities.

I fully understand that this project, as originally envisioned and ultimately executed, will provide little to no value to either baseball or the field of ornithology. If I found something that others consider useful or beneficial, that's great! But it is not and was never the point. The point is skill building and having fun bringing together worlds that probably don't interact very often and seeing what happens. I should also note that I love baseball but I'm not a bird watcher or bird hobbyist or anything, so I must beg forgiveness for any affronts to the field of ornithology that this site almost certainly contains.

What did I find? Take a look around and find out!
